// Code generated by cmd/reset. DO NOT EDIT.

package example

func (s *ResetableStruct) Reset() {
	if s == nil {
		return
	}
	s.i = 0
	s.str = ""
	if s.strP != nil {
		*s.strP = ""
	}
	s.s = s.s[:0]
	if s.m != nil {
		for k := range s.m {
			delete(s.m, k)
		}
	}
	if s.child != nil {
		if resetter, ok := interface{}(s.child).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}
