syntax = "proto3";

package shortener;

option go_package = "github.com/BuJIKuH/go-musthave-shortener-tpl/internal/proto;shortener";

import "google/protobuf/empty.proto";

// ShortenerService предоставляет API сокращения URL через gRPC.
service ShortenerService {
  // ShortenURL сокращает переданный URL и возвращает короткий идентификатор.
  rpc ShortenURL(URLShortenRequest) returns (URLShortenResponse);

  // ExpandURL возвращает оригинальный URL по короткому идентификатору.
  rpc ExpandURL(URLExpandRequest) returns (URLExpandResponse);

  // ListUserURLs возвращает список всех URL пользователя.
  rpc ListUserURLs(google.protobuf.Empty) returns (UserURLsResponse);
}

// URLShortenRequest содержит оригинальный URL для сокращения.
message URLShortenRequest {
  string url = 1;
}

// URLShortenResponse возвращает короткий идентификатор URL.
message URLShortenResponse {
  string result = 1;
}

// URLExpandRequest содержит короткий идентификатор URL.
message URLExpandRequest {
  string id = 1;
}

// URLExpandResponse возвращает оригинальный URL по короткому идентификатору.
message URLExpandResponse {
  string result = 1;
}

// UserURLsResponse возвращает список всех URL пользователя.
message UserURLsResponse {
  repeated URLData url = 1;
}

// URLData содержит короткий и оригинальный URL.
message URLData {
  string short_url = 1;
  string original_url = 2;
}